import anthropicProxyRoutesV2 from "./proxy/routesv2/anthropic";
import azureProxyRoutesV2 from "./proxy/routesv2/azure";
import bedrockProxyRoutesV2 from "./proxy/routesv2/bedrock";
import cerebrasProxyRoutesV2 from "./proxy/routesv2/cerebras";
import cohereProxyRoutesV2 from "./proxy/routesv2/cohere";
import deepseekProxyRoutesV2 from "./proxy/routesv2/deepseek";
import geminiProxyRoutesV2 from "./proxy/routesv2/gemini";
import groqProxyRoutesV2 from "./proxy/routesv2/groq";
import minimaxProxyRoutesV2 from "./proxy/routesv2/minimax";
import mistralProxyRoutesV2 from "./proxy/routesv2/mistral";
import ollamaProxyRoutesV2 from "./proxy/routesv2/ollama";
import openAiProxyRoutesV2 from "./proxy/routesv2/openai";
import openrouterProxyRoutesV2 from "./proxy/routesv2/openrouter";
import perplexityProxyRoutesV2 from "./proxy/routesv2/perplexity";
import vllmProxyRoutesV2 from "./proxy/routesv2/vllm";
import xaiProxyRoutesV2 from "./proxy/routesv2/xai";
import zhipuaiProxyRoutesV2 from "./proxy/routesv2/zhipuai";

export { default as browserStreamRoutes } from "@/features/browser-stream/routes/browser-stream.routes";
export { default as a2aRoutes } from "./a2a";
export { default as agentRoutes } from "./agent";
export { default as agentToolRoutes } from "./agent-tool";
export { default as apiKeyRoutes } from "./api-key";
export { default as authRoutes } from "./auth";
export { default as autonomyPolicyRoutes } from "./autonomy-policies";
export { default as chatRoutes } from "./chat/routes";
export { default as chatopsRoutes } from "./chatops";
export { default as configRoutes } from "./config";
export { default as healthRoutes } from "./health";
export { default as incomingEmailRoutes } from "./incoming-email";
export { default as interactionRoutes } from "./interaction";
export { default as internalMcpCatalogRoutes } from "./internal-mcp-catalog";
export { default as invitationRoutes } from "./invitation";
export { default as knowledgeBaseRoutes } from "./knowledge-base";
export { default as limitsRoutes } from "./limits";
export { default as llmProviderApiKeyRoutes } from "./llm-provider-api-keys";
export { default as llmModelsRoutes } from "./llm-provider-models";
export { mcpGatewayRoutes } from "./mcp-gateway";
export { mcpProxyRoutes } from "./mcp-proxy";
export { default as mcpServerRoutes } from "./mcp-server";
export { default as mcpServerInstallationRequestRoutes } from "./mcp-server-installation-requests";
export { default as mcpToolCallRoutes } from "./mcp-tool-call";
export { default as memberRoutes } from "./member";
export { default as oauthRoutes } from "./oauth";
export { default as oauthServerRoutes } from "./oauth-server";
export { default as optimizationRuleRoutes } from "./optimization-rule";
export { default as organizationRoutes } from "./organization";
export { default as organizationRoleRoutes } from "./organization-role";
export { default as scheduleTriggerRoutes } from "./schedule-trigger";
export { default as virtualApiKeysRoutes } from "./virtual-api-keys";
// Proxy routes
export const anthropicProxyRoutes = anthropicProxyRoutesV2;
export const azureProxyRoutes = azureProxyRoutesV2;
export const cerebrasProxyRoutes = cerebrasProxyRoutesV2;
export const cohereProxyRoutes = cohereProxyRoutesV2;
export const geminiProxyRoutes = geminiProxyRoutesV2;
export const mistralProxyRoutes = mistralProxyRoutesV2;
export const perplexityProxyRoutes = perplexityProxyRoutesV2;
export const groqProxyRoutes = groqProxyRoutesV2;
export const xaiProxyRoutes = xaiProxyRoutesV2;
export const openAiProxyRoutes = openAiProxyRoutesV2;
export const openrouterProxyRoutes = openrouterProxyRoutesV2;
export const vllmProxyRoutes = vllmProxyRoutesV2;
export const ollamaProxyRoutes = ollamaProxyRoutesV2;
export const deepseekProxyRoutes = deepseekProxyRoutesV2;
export const zhipuaiProxyRoutes = zhipuaiProxyRoutesV2;
// Bedrock proxy routes - V2 only (unified handler, AWS Converse API)
export const bedrockProxyRoutes = bedrockProxyRoutesV2;
// MiniMax proxy routes - V2 only (new provider, no legacy v1)
export const minimaxProxyRoutes = minimaxProxyRoutesV2;
export { default as secretsRoutes } from "./secrets";
export { default as statisticsRoutes } from "./statistics";
export { default as teamRoutes } from "./team";
export { default as tokenRoutes } from "./token";
export { default as toolRoutes } from "./tool";
export { default as userRoutes } from "./user";
export { default as userTokenRoutes } from "./user-token";
